//
//  DepartmentServices.swift
//  lyie
//
//  Created by Sevcan Eşim on 11.01.2021.
//

import Foundation
import UIKit

struct DepartmentServices {
    var id: Int
    var name: String
    
    static func allDepartmentList() -> [DepartmentServices] {
        return [DepartmentServices(id: 0, name: "Acil Yardım ve Afet Bölümü"),
                DepartmentServices(id: 1, name: "Ağaç İşleri Endüstri Mühendisliği Bölümü"),
                DepartmentServices(id: 2, name: "Aile ve Tüketici Bilimleri Bölümü"),
                DepartmentServices(id: 3, name: "Aktüerya Bölümü"),
                DepartmentServices(id: 4, name: "Alman Dili ve Edebiyatı Bölümü"),
                DepartmentServices(id: 5, name: "Almanca Öğretmenliği Bölümü"),
                DepartmentServices(id: 6, name: "Amerikan Kültürü ve Edebiyatı Bölümü"),
                DepartmentServices(id: 7, name: "Animasyon Bölümü"),
                DepartmentServices(id: 8, name: "Antrenörlük Eğitimi Bölümü"),
                DepartmentServices(id: 9, name: "Antropoloji Bölümü"),
                DepartmentServices(id: 10, name: "Arap Dili ve Edebiyatı Bölümü"),
                DepartmentServices(id: 11, name: "Arapça Öğretmenliği Bölümü"),
                DepartmentServices(id: 12, name: "Arkeoloji Bölümü"),
                DepartmentServices(id: 13, name: "Arnavut Dili ve Edebiyatı Bölümü"),
                DepartmentServices(id: 14, name: "Astronomi ve Uzay Bilimleri Bölümü"),
                DepartmentServices(id: 15, name: "Avrupa Birliği İlişkileri Bölümü"),
                DepartmentServices(id: 16, name: "Azerbaycan Dili ve Edebiyatı Bölümü"),
                DepartmentServices(id: 17, name: "Bahçe Bitkileri Bölümü"),
                DepartmentServices(id: 18, name: "Balıkçılık Teknolojisi Mühendisliği"),
                DepartmentServices(id: 19, name: "Bankacılık Bölümü"),
                DepartmentServices(id: 20, name: "Bankacılık ve Finans Bölümü"),
                DepartmentServices(id: 21, name: "Bankacılık ve Finansman Bölümü"),
                DepartmentServices(id: 22, name: "Basın ve Yayın Bölümü"),
                DepartmentServices(id: 23, name: "Beden Eğitimi ve Spor Öğretmenliği Bölümü"),
                DepartmentServices(id: 24, name: "Beslenme ve Diyetetik Bölümü"),
                DepartmentServices(id: 25, name: "Bilgi ve Belge Yönetimi Bölümü"),
                DepartmentServices(id: 26, name: "Bilgisayar Teknolojisi ve Bilişim Sistemleri Bölümü"),
                DepartmentServices(id: 27, name: "Bilgisayar Bilimleri ve Mühendisliği Bölümü"),
                DepartmentServices(id: 28, name: "Bilgisayar Mühendisliği Bölümü"),
                DepartmentServices(id: 29, name: "Bilgisayar ve Enformasyon Sistemleri Bölümü"),
                DepartmentServices(id: 30, name: "Bilgisayar ve Öğretim Teknolojileri Öğretmenliği"),
                DepartmentServices(id: 31, name: "Bilgisayar ve Yazılım Mühendisliği"),
                DepartmentServices(id: 32, name: "Bilgisayar-Enformatik Bölümü"),
                DepartmentServices(id: 33, name: "Bilim Tarihi Bölümü"),
                DepartmentServices(id: 34, name: "Bilişim Sistemleri Mühendisliği Bölümü"),
                DepartmentServices(id: 35, name: "Bilişim Sistemleri ve Teknolojileri Bölümü"),
                DepartmentServices(id: 36, name: "Bitki Koruma Bölümü"),
                DepartmentServices(id: 37, name: "Bitkisel Üretim ve Teknolojileri Bölümü"),
                DepartmentServices(id: 38, name: "Biyoenformatik ve Genetik Bölümü"),
                DepartmentServices(id: 39, name: "Biyokimya Bölümü"),
                DepartmentServices(id: 40, name: "Biyoloji Bölümü"),
                DepartmentServices(id: 41, name: "Biyoloji Öğretmenliği Bölümü"),
                DepartmentServices(id: 42, name: "Biyomedikal Mühendisliği Bölümü"),
                DepartmentServices(id: 43, name: "Biyomühendislik Bölümü"),
                DepartmentServices(id: 44, name: "Biyosistem Mühendisliği Bölümü"),
                DepartmentServices(id: 45, name: "Biyoteknoloji ile Biyoteknoloji ve Moleküler Biyoloji Bölümü"),
                DepartmentServices(id: 46, name: "Boşnak Dili ve Edebiyatı Bölümü"),
                DepartmentServices(id: 47, name: "Bulgar Dili ve Edebiyatı Bölümü"),
                DepartmentServices(id: 48, name: "Canlandırma Filmi Tasarım ve Yönetimi Bölümü"),
                DepartmentServices(id: 49, name: "Cevher Hazırlama Mühendisliği Bölümü"),
                DepartmentServices(id: 50, name: "Coğrafya Bölümü"),
                DepartmentServices(id: 51, name: "Coğrafya Öğretmenliği Bölümü"),
                DepartmentServices(id: 52, name: "Çağdaş Türk Lehçeleri ve Edebiyatları Bölümü"),
                DepartmentServices(id: 53, name: "Çağdaş Yunan Dili ve Edebiyatı Bölümü"),
                DepartmentServices(id: 54, name: "Çalışma Ekonomisi ve Endüstri İlişkileri Bölümü"),
                DepartmentServices(id: 55, name: "Çerkez Dili ve Edebiyatı Bölümü"),
                DepartmentServices(id: 56, name: "Çeviribilim Bölümü"),
                DepartmentServices(id: 57, name: "Çevre Mühendisliği Bölümü"),
                DepartmentServices(id: 58, name: "Çin Dili ve Edebiyatı Bölümü"),
                DepartmentServices(id: 59, name: "Çocuk Gelişimi Bölümü"),
                DepartmentServices(id: 60, name: "Deniz İşletmeciliği ve Yönetimi Bölümü"),
                DepartmentServices(id: 61, name: "Deniz Ulaştırma İşletme Mühendisliği Bölümü"),
                DepartmentServices(id: 62, name: "Denizcilik İşletmeleri Yönetimi Bölümü"),
                DepartmentServices(id: 63, name: "Deri Mühendisliği Bölümü"),
                DepartmentServices(id: 64, name: "Dijital Oyun Tasarımı Bölümü"),
                DepartmentServices(id: 65, name: "Dil ve Konuşma Terapisi Bölümü"),
                DepartmentServices(id: 66, name: "Dilbilim Bölümü"),
                DepartmentServices(id: 67, name: "Dini İlimler Bölümü"),
                DepartmentServices(id: 68, name: "Diş Hekimliği Fakültesi Bölümü"),
                DepartmentServices(id: 69, name: "Doğu Dilleri Bölümü"),
                DepartmentServices(id: 70, name: "Ebelik Bölümü"),
                DepartmentServices(id: 71, name: "Eczacılık Fakültesi Bölümü"),
                DepartmentServices(id: 72, name: "Ekonometri Bölümü"),
                DepartmentServices(id: 73, name: "Ekonomi Bölümü"),
                DepartmentServices(id: 74, name: "Ekonomi ve Finans Bölümü"),
                DepartmentServices(id: 75, name: "El Sanatları Bölümü"),
                DepartmentServices(id: 76, name: "Elektrik Mühendisliği Bölümü"),
                DepartmentServices(id: 77, name: "Elektrik-Elektronik Mühendisliği Bölümü"),
                DepartmentServices(id: 78, name: "Elektronik Mühendisliği Bölümü"),
                DepartmentServices(id: 79, name: "Elektronik ve Haberleşme Mühendisliği Bölümü"),
                DepartmentServices(id: 80, name: "Endüstri Mühendisliği Bölümü"),
                DepartmentServices(id: 81, name: "Endüstri Mühendisliği Programları Bölümü"),
                DepartmentServices(id: 82, name: "Endüstri Tasarımı Bölümü"),
                DepartmentServices(id: 83, name: "Endüstri Ürünleri Tasarımı Bölümü"),
                DepartmentServices(id: 84, name: "Endüstri ve Sistem Mühendisliği Bölümü"),
                DepartmentServices(id: 85, name: "Endüstriyel Tasarım Bölümü"),
                DepartmentServices(id: 86, name: "Endüstriyel Tasarım Mühendisliği Bölümü"),
                DepartmentServices(id: 87, name: "Enerji Sistemleri Mühendisliği Bölümü"),
                DepartmentServices(id: 88, name: "Enerji ve Malzeme Mühendisliği Bölümü"),
                DepartmentServices(id: 89, name: "Enerji Yönetimi Bölümü"),
                DepartmentServices(id: 90, name: "Ergoterapi Bölümü"),
                DepartmentServices(id: 91, name: "Ermeni Dili ve Edebiyatı Bölümü"),
                DepartmentServices(id: 92, name: "Eski Yunan Dili ve Edebiyatı Bölümü"),
                DepartmentServices(id: 93, name: "Enformasyon Teknolojileri Bölümü"),
                DepartmentServices(id: 94, name: "Eşit Ağırlıklı Programlar Bölümü"),
                DepartmentServices(id: 95, name: "Fars Dili ve Edebiyatı Bölümü"),
                DepartmentServices(id: 96, name: "Felsefe Bölümü"),
                DepartmentServices(id: 97, name: "Felsefe Grubu Öğretmenliği Bölümü"),
                DepartmentServices(id: 98, name: "Fen Bilgisi Öğretmenliği Bölümü"),
                DepartmentServices(id: 99, name: "Film Tasarım ve Yazarlık Bölümü"),
                DepartmentServices(id: 100, name: "Film Tasarım ve Yönetmenliği Bölümü"),
                DepartmentServices(id: 101, name: "Film Tasarımı Bölümü"),
                DepartmentServices(id: 102, name: "Finansal Ekonometri Bölümü"),
                DepartmentServices(id: 103, name: "Fizik Bölümü"),
                DepartmentServices(id: 104, name: "Fizik Mühendisliği Bölümü"),
                DepartmentServices(id: 105, name: "Fizik Öğretmenliği Bölümü"),
                DepartmentServices(id: 106, name: "Fizyoterapi ve Rehabilitasyon Bölümü"),
                DepartmentServices(id: 107, name: "Fotoğraf ve Video Bölümü"),
                DepartmentServices(id: 108, name: "Fransız Dili ve Edebiyatı Bölümü"),
                DepartmentServices(id: 109, name: "Fransızca Öğretmenliği Bölümü"),
                DepartmentServices(id: 110, name: "Gastronomi Bölümü"),
                DepartmentServices(id: 111, name: "Gastronomi ve Mutfak Sanatları Bölümü"),
                DepartmentServices(id: 112, name: "Gayrimenkul ve Varlık Değerleme Bölümü"),
                DepartmentServices(id: 113, name: "Gazetecilik Bölümü"),
                DepartmentServices(id: 114, name: "Geleneksel Türk Sanatları (M.T.O.K.) Bölümü"),
                DepartmentServices(id: 115, name: "Gemi İnşaatı ve Gemi Makineleri Mühendisliği Bölümü"),
                DepartmentServices(id: 116, name: "Gemi Makineleri İşletme Mühendisliği Bölümü"),
                DepartmentServices(id: 117, name: "Gemi ve Deniz Teknolojisi Mühendisliği Bölümü"),
                DepartmentServices(id: 118, name: "Gemi ve Yat Tasarımı Bölümü"),
                DepartmentServices(id: 119, name: "Genetik ve Biyomühendislik Bölümü"),
                DepartmentServices(id: 120, name: "Geomatik Mühendisliği Bölümü"),
                DepartmentServices(id: 121, name: "Gerontoloji Bölümü"),
                DepartmentServices(id: 122, name: "Gıda Mühendisliği Bölümü"),
                DepartmentServices(id: 123, name: "Gıda Teknolojisi Bölümü"),
                DepartmentServices(id: 124, name: "Girişimcilik Bölümü"),
                DepartmentServices(id: 125, name: "Görme Engelliler Öğretmenliği Bölümü"),
                DepartmentServices(id: 126, name: "Görsel İletişim Tasarımı Bölümü"),
                DepartmentServices(id: 127, name: "Görsel Sanatlar Bölümü"),
                DepartmentServices(id: 128, name: "Görsel Sanatlar ve Görsel İletişim Tasarımı Bölümü"),
                DepartmentServices(id: 129, name: "Grafik Tasarım Bölümü"),
                DepartmentServices(id: 130, name: "Gümrük İşletme Bölümü"),
                DepartmentServices(id: 131, name: "Gürcü Dili ve Edebiyatı Bölümü"),
                DepartmentServices(id: 132, name: "Güverte Bölümü"),
                DepartmentServices(id: 133, name: "Halkbilim Bölümü"),
                DepartmentServices(id: 134, name: "Halkla İlişkiler Bölümü"),
                DepartmentServices(id: 135, name: "Halkla İlişkiler ve Reklamcılık Bölümü"),
                DepartmentServices(id: 136, name: "Halkla İlişkiler ve Tanıtım Bölümü"),
                DepartmentServices(id: 137, name: "Harita Mühendisliği Bölümü"),
                DepartmentServices(id: 138, name: "Havacılık Elektrik ve Elektroniği Bölümü"),
                DepartmentServices(id: 139, name: "Havacılık İşletmeciliği Bölümü"),
                DepartmentServices(id: 140, name: "Havacılık ve Uzay Mühendisliği Bölümü"),
                DepartmentServices(id: 141, name: "Hayvansal Üretim Bölümü"),
                DepartmentServices(id: 142, name: "Hemşirelik Bölümü"),
                DepartmentServices(id: 143, name: "Hemşirelik ve Sağlık Hizmetleri Bölümü"),
                DepartmentServices(id: 144, name: "Hidrojeoloji Mühendisliği Bölümü"),
                DepartmentServices(id: 145, name: "Hindoloji Bölümü"),
                DepartmentServices(id: 146, name: "Hititoloji Bölümü"),
                DepartmentServices(id: 147, name: "Hukuk Fakültesi Bölümü"),
                DepartmentServices(id: 148, name: "Hungaroloji Bölümü"),
                DepartmentServices(id: 149, name: "İbrani Dili ve Edebiyatı Bölümü"),
                DepartmentServices(id: 150, name: "İç Mimarlık Bölümü"),
                DepartmentServices(id: 151, name: "İç Mimarlık ve Çevre Tasarımı Bölümü"),
                DepartmentServices(id: 152, name: "İktisat Bölümü"),
                DepartmentServices(id: 153, name: "İktisadi ve İdari Bilimler Bölümü"),
                DepartmentServices(id: 154, name: "İlahiyat Fakültesi Bölümü"),
                DepartmentServices(id: 155, name: "İletişim Bilimleri Bölümü"),
                DepartmentServices(id: 156, name: "İletişim Sanatları Bölümü"),
                DepartmentServices(id: 157, name: "İletişim Tasarımı Bölümü"),
                DepartmentServices(id: 158, name: "İletişim Tasarımı ve Medya Bölümü"),
                DepartmentServices(id: 159, name: "İletişim Tasarımı ve Yönetimi Bölümü"),
                DepartmentServices(id: 160, name: "İletişim ve Tasarım Bölümü"),
                DepartmentServices(id: 161, name: "İlköğretim Matematik Öğretmenliği Bölümü"),
                DepartmentServices(id: 162, name: "İmalat Mühendisliği Bölümü"),
                DepartmentServices(id: 163, name: "İngiliz Dil Bilimi Bölümü"),
                DepartmentServices(id: 164, name: "İngiliz Dili ve Edebiyatı Bölümü"),
                DepartmentServices(id: 165, name: "İngiliz Dili ve Karşılaştırmalı Edebiyat Bölümü"),
                DepartmentServices(id: 166, name: "İngilizce Öğretmenliği Bölümü"),
                DepartmentServices(id: 167, name: "İnsan Kaynakları Yönetimi Bölümü"),
                DepartmentServices(id: 168, name: "İnsan ve Toplum Bilimleri Bölümü"),
                DepartmentServices(id: 169, name: "İnşaat Mühendisliği Bölümü"),
                DepartmentServices(id: 170, name: "İslam Bilimleri Bölümü"),
                DepartmentServices(id: 171, name: "İslam ve Din Bilimleri Bölümü"),
                DepartmentServices(id: 172, name: "İslami İlimler Bölümü"),
                DepartmentServices(id: 173, name: "İspanyol Dili ve Edebiyatı Bölümü"),
                DepartmentServices(id: 174, name: "İstatistik Bölümü"),
                DepartmentServices(id: 175, name: "İstatistik ve Bilgisayar Bilimleri Bölümü"),
                DepartmentServices(id: 176, name: "İş Sağlığı ve Güvenliği Bölümü"),
                DepartmentServices(id: 177, name: "İşitme Engelliler Öğretmenliği Bölümü"),
                DepartmentServices(id: 178, name: "İşletme Bölümü"),
                DepartmentServices(id: 179, name: "İşletme Bilgi Yönetimi Bölümü"),
                DepartmentServices(id: 180, name: "İşletme Enformatiği Bölümü"),
                DepartmentServices(id: 181, name: "İşletme Mühendisliği Bölümü"),
                DepartmentServices(id: 182, name: "İşletme Yönetimi Bölümü"),
                DepartmentServices(id: 183, name: "İşletme-Ekonomi Bölümü"),
                DepartmentServices(id: 184, name: "İtalyan Dili ve Edebiyatı Bölümü"),
                DepartmentServices(id: 185, name: "Japon Dili ve Edebiyatı Bölümü"),
                DepartmentServices(id: 186, name: "Japonca Öğretmenliği Bölümü"),
                DepartmentServices(id: 187, name: "Jeofizik Mühendisliği Bölümü"),
                DepartmentServices(id: 188, name: "Jeoloji Mühendisliği Bölümü"),
                DepartmentServices(id: 189, name: "Kamu Yönetimi Bölümü"),
                DepartmentServices(id: 190, name: "Kanatlı Hayvan Yetiştiriciliği Bölümü"),
                DepartmentServices(id: 191, name: "Karşılaştırmalı Edebiyat Bölümü"),
                DepartmentServices(id: 192, name: "Kazak Dili ve Edebiyatı Bölümü"),
                DepartmentServices(id: 193, name: "Kentsel Tasarım ve Peyzaj Bölümü"),
                DepartmentServices(id: 194, name: "Kentsel Tasarım ve Peyzaj Mimarlığı Bölümü"),
                DepartmentServices(id: 195, name: "Kimya Bölümü"),
                DepartmentServices(id: 196, name: "Kimya Mühendisliği Bölümü"),
                DepartmentServices(id: 197, name: "Kimya Mühendisliği ve Uygulamalı Kimya Bölümü"),
                DepartmentServices(id: 198, name: "Kimya Öğretmenliği Bölümü"),
                DepartmentServices(id: 199, name: "Kimya ve Süreç Mühendisliği Bölümü"),
                DepartmentServices(id: 200, name: "Kimya-Biyoloji Mühendisliği Bölümü"),
                DepartmentServices(id: 201, name: "Klasik Arkeoloji Bölümü"),
                DepartmentServices(id: 202, name: "Konaklama İşletmeciliği Bölümü"),
                DepartmentServices(id: 203, name: "Konaklama ve Turizm İşletmeciliği Bölümü"),
                DepartmentServices(id: 204, name: "Kontrol ve Otomasyon Mühendisliği Bölümü"),
                DepartmentServices(id: 205, name: "Kore Dili ve Edebiyatı Bölümü"),
                DepartmentServices(id: 206, name: "Kurgu-Ses ve Görüntü Yönetimi Bölümü"),
                DepartmentServices(id: 207, name: "Kuyumculuk ve Mücevher Tasarımı Bölümü"),
                DepartmentServices(id: 208, name: "Kültür Varlıklarını Koruma ve Onarım Bölümü"),
                DepartmentServices(id: 209, name: "Küresel Siyaset ve Uluslararası İlişkiler Bölümü"),
                DepartmentServices(id: 210, name: "Kürt Dili ve Edebiyatı Bölümü"),
                DepartmentServices(id: 211, name: "Latin Dili ve Edebiyatı Bölümü"),
                DepartmentServices(id: 212, name: "Leh Dili ve Edebiyatı Bölümü"),
                DepartmentServices(id: 213, name: "Lif ve Polimer Mühendisliği Bölümü"),
                DepartmentServices(id: 214, name: "Lojistik Bölümü"),
                DepartmentServices(id: 215, name: "Lojistik ve Taşımacılık Bölümü"),
                DepartmentServices(id: 216, name: "Lojistik Yönetimi Bölümü"),
                DepartmentServices(id: 217, name: "Maden Mühendisliği Bölümü"),
                DepartmentServices(id: 218, name: "Makine Mühendisliği Bölümü"),
                DepartmentServices(id: 219, name: "Makine ve İmalat Mühendisliği Bölümü"),
                DepartmentServices(id: 220, name: "Makine ve Malzeme Mühendisliği Bölümü"),
                DepartmentServices(id: 221, name: "Maliye Bölümü"),
                DepartmentServices(id: 222, name: "Malzeme Bilimi ve Mühendisliği Bölümü"),
                DepartmentServices(id: 223, name: "Malzeme Bilimi ve Nanoteknoloji Mühendisliği Bölümü"),
                DepartmentServices(id: 224, name: "Malzeme Mühendisliği Bölümü"),
                DepartmentServices(id: 225, name: "Matematik Bölümü"),
                DepartmentServices(id: 226, name: "Matematik Mühendisliği Bölümü"),
                DepartmentServices(id: 227, name: "Matematik Öğretmenliği Bölümü"),
                DepartmentServices(id: 228, name: "Matematik ve Bilgisayar Bilimleri Bölümü"),
                DepartmentServices(id: 229, name: "Matematik-Bilgisayar Bölümü"),
                DepartmentServices(id: 230, name: "Medya ve Görsel Sanatlar Bölümü"),
                DepartmentServices(id: 231, name: "Medya ve İletişim Bölümü"),
                DepartmentServices(id: 232, name: "Medya ve İletişim Sistemleri Bölümü"),
                DepartmentServices(id: 233, name: "Mekatronik Mühendisliği Bölümü"),
                DepartmentServices(id: 234, name: "Mekatronik Sistemler Mühendisliği Bölümü"),
                DepartmentServices(id: 235, name: "Metalurji ve Malzeme Mühendisliği Bölümü"),
                DepartmentServices(id: 236, name: "Meteoroloji Mühendisliği Bölümü"),
                DepartmentServices(id: 237, name: "Mimarlık Bölümü"),
                DepartmentServices(id: 238, name: "Mobilya Üretimi ve İç Mekan Tasarımı Bölümü"),
                DepartmentServices(id: 239, name: "Moda Tasarımı Bölümü"),
                DepartmentServices(id: 240, name: "Moda ve Tekstil Tasarımı Bölümü"),
                DepartmentServices(id: 241, name: "Moleküler Biyoloji ve Genetik Bölümü"),
                DepartmentServices(id: 242, name: "Muhasebe Bölümü"),
                DepartmentServices(id: 243, name: "Muhasebe Bilgi Sistemleri Bölümü"),
                DepartmentServices(id: 244, name: "Muhasebe ve Denetim Bölümü"),
                DepartmentServices(id: 245, name: "Muhasebe ve Finans Yönetimi Bölümü"),
                DepartmentServices(id: 246, name: "Mücevherat Mühendisliği Bölümü"),
                DepartmentServices(id: 247, name: "Mühendislik Programları Bölümü"),
                DepartmentServices(id: 248, name: "Mühendislik ve Doğa Bilimleri Programları Bölümü"),
                DepartmentServices(id: 249, name: "Mütercim-Tercümanlık Bölümü"),
                DepartmentServices(id: 250, name: "Müzecilik Bölümü"),
                DepartmentServices(id: 251, name: "Nanoteknoloji Mühendisliği Bölümü"),
                DepartmentServices(id: 252, name: "Nükleer Enerji Mühendisliği Bölümü"),
                DepartmentServices(id: 253, name: "Odyoloji Bölümü"),
                DepartmentServices(id: 254, name: "Okul Öncesi Öğretmenliği Bölümü"),
                DepartmentServices(id: 255, name: "Optik ve Akustik Mühendisliği Bölümü"),
                DepartmentServices(id: 256, name: "Organik Tarım İşletmeciliği Bölümü"),
                DepartmentServices(id: 257, name: "Orman Endüstrisi Mühendisliği Bölümü"),
                DepartmentServices(id: 258, name: "Orman Mühendisliği Bölümü"),
                DepartmentServices(id: 259, name: "Ortez-Protez Bölümü"),
                DepartmentServices(id: 260, name: "Otel Yöneticiliği Bölümü"),
                DepartmentServices(id: 261, name: "Otomotiv Mühendisliği Bölümü"),
                DepartmentServices(id: 262, name: "Öğretmenlik Programları Bölümü"),
                DepartmentServices(id: 263, name: "Özel Eğitim Öğretmenliği Bölümü"),
                DepartmentServices(id: 264, name: "Pazarlama Bölümü"),
                DepartmentServices(id: 265, name: "Perfüzyon Bölümü"),
                DepartmentServices(id: 266, name: "Petrol ve Doğalgaz Mühendisliği Bölümü"),
                DepartmentServices(id: 267, name: "Peyzaj Mimarlığı Bölümü"),
                DepartmentServices(id: 268, name: "Pilot Eğitimi Bölümü"),
                DepartmentServices(id: 269, name: "Pilotaj Bölümü"),
                DepartmentServices(id: 270, name: "Polimer Mühendisliği Bölümü"),
                DepartmentServices(id: 271, name: "Polonya Dili ve Kültürü Bölümü"),
                DepartmentServices(id: 272, name: "Protohistorya Bölümü"),
                DepartmentServices(id: 273, name: "Protohistorya ve Ön Asya Arkeolojisi Bölümü"),
                DepartmentServices(id: 274, name: "Psikoloji Bölümü"),
                DepartmentServices(id: 275, name: "Psikolojik Danışmanlık ve Rehberlik Bölümü"),
                DepartmentServices(id: 276, name: "Radyo ve Televizyon Bölümü")]
    }
    
    static func getDepartmentName(by id: Int) -> String {
        switch id {
        default:
            return DepartmentServices.allDepartmentList()[id].name
        }
    }
}




