//
//  HighSchoolServices.swift
//  lyie
//
//  Created by Sevcan Eşim on 10.01.2021.
//

import Foundation
import UIKit

struct HighSchoolServices {
    var id: Int
    var name: String
    var licensePlateId: Int
    
    static func allHighSchoolList() -> [HighSchoolServices] {
        return [HighSchoolServices(id: 0, name: "ADANA ŞEHİT ALİ ÖZTAŞ ANADOLU LİSESİ", licensePlateId: 1),
                HighSchoolServices(id: 1, name: "ADANA KURTTEPE ANADOLU LİSESİ", licensePlateId: 1),
                HighSchoolServices(id: 2, name: "ADANA ÇUKUROVA ELEKTRİK MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 1),
                HighSchoolServices(id: 3, name: "ADANA TİCARET ODASI ANADOLU LİSESİ", licensePlateId: 1),
                HighSchoolServices(id: 4, name: "ADANA PİRİ REİS ANADOLU LİSESİ", licensePlateId: 1),
                HighSchoolServices(id: 5, name: "ADANA ÇEAŞ ANADOLU LİSESİ", licensePlateId: 1),
                HighSchoolServices(id: 6, name: "ADANA TOKİ KÖPRÜLÜ ANADOLU LİSESİ", licensePlateId: 1),
                HighSchoolServices(id: 7, name: "ADANA İSMAİL KULAK ANADOLU LİSESİ", licensePlateId: 1),
                HighSchoolServices(id: 8, name: "ADANA İSMAİL SAFA ÖZER ANADOLU LİSESİ", licensePlateId: 1),
                HighSchoolServices(id: 9, name: "ADANA ŞEHİT TEMEL CİNGÖZ ANADOLU LİSESİ", licensePlateId: 1),
                HighSchoolServices(id: 10, name: "AKSARAY HAZIM KULAK ANADOLU LİSESİ", licensePlateId: 68),
                HighSchoolServices(id: 11, name: "AKSARAY ŞEHİT ALİ ER ANADOLU LİSESİ", licensePlateId: 68),
                HighSchoolServices(id: 12, name: "AKSARAY KANBER DEMİR ANADOLU LİSESİ", licensePlateId: 68),
                HighSchoolServices(id: 13, name: "AKSARAY OSMAN GAZİ ANADOLU LİSESİ", licensePlateId: 68),
                HighSchoolServices(id: 14, name: "AKSARAY ATATÜRK ANADOLU LİSESİ", licensePlateId: 68),
                HighSchoolServices(id: 15, name: "ANKARA ATATÜRK LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 16, name: "ANKARA ATATÜRK ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 17, name: "ANKARA DR. RIDVAN EGE DR. BİNNAZ EGE ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 18, name: "ANKARA FETHİYE KEMAL MUMCU ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 19, name: "ANKARA BEKİR GÖKDAĞ ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 20, name: "ANKARA REHA ALEMDAROĞLU ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 21, name: "ANKARA MUSTAFA KEMAL ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 22, name: "ANKARA YAVUZ SULTAN SELİM ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 23, name: "ANKARA MEHMET EMİN RESULZADE ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 24, name: "ANKARA MUSTAFA AZMİ DOĞAN ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 25, name: "ANKARA PROFESÖR DR. ŞEVKET RAŞİT HATİPOĞLU ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 26, name: "ANKARA BATIKENT LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 27, name: "ANKARA LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 28, name: "ANKARA MİMAR KEMAL ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 29, name: "ANKARA BAHÇELİEVLER ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 30, name: "ANKARA HASAN ALİ YÜCEL SOSYAL BİLİMLER LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 31, name: "ANKARA CUMHURİYET ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 32, name: "ANKARA AYRANCI AYSEL YÜCETÜRK ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 33, name: "ANKARA ÖMER SEYFETTİN ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 34, name: "ANKARA SOKULLU MEHMET PAŞA ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 35, name: "ANKARA İNÖNÜ ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 36, name: "ANKARA HÜRRİYET ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 37, name: "ANKARA BAHÇELİEVLER DENEME ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 38, name: "ANKARA BETÜL CAN ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 39, name: "ANKARA SERÇEV ENGELSİZ MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 40, name: "ANKARA AYHAN SÜMER ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 41, name: "ANKARA TINAZTEPE LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 42, name: "ANKARA YAHYA KEMAL BEYATLI ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 43, name: "ANKARA ETLİK ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 44, name: "ANKARA MUSA ERDEM ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 45, name: "ANKARA NERMİN MEHMET ÇEKİÇ ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 46, name: "ANKARA KURTULUŞ ANADOLU LİSESİ", licensePlateId: 6),
                HighSchoolServices(id: 47, name: "ANKARA ÇANKAYA ANADOLU LİSESİ (SEYRANBAĞLARI)", licensePlateId: 6),
                HighSchoolServices(id: 48, name: "ANTALYA AHMET FEVZİ ALAETTİNOĞLU ANADOLU LİSESİ", licensePlateId: 7),
                HighSchoolServices(id: 49, name: "ANTALYA ŞEHİT ABDULLAH ÜMİT SERCAN ANADOLU LİSESİ", licensePlateId: 7),
                HighSchoolServices(id: 50, name: "ANTALYA 15 TEMMUZ ŞEHİTLER ANADOLU LİSESİ", licensePlateId: 7),
                HighSchoolServices(id: 51, name: "ANTALYA NİMET ALAETTİNOĞLU ANADOLU LİSESİ", licensePlateId: 7),
                HighSchoolServices(id: 52, name: "ANTALYA ABDURRAHMAN ALAATTİNOĞLU ANADOLU LİSESİ", licensePlateId: 7),
                HighSchoolServices(id: 53, name: "ANTALYA OBA NAZMİ YILMAZ ANADOLU LİSESİ", licensePlateId: 7),
                HighSchoolServices(id: 54, name: "BALIKESİR LİSESİ", licensePlateId: 10),
                HighSchoolServices(id: 55, name: "BALIKESİR FATMA EMİN KUTVAR ANADOLU LİSESİ", licensePlateId: 10),
                HighSchoolServices(id: 56, name: "BALIKESİR RAHMİ KULA ANADOLU LİSESİ", licensePlateId: 10),
                HighSchoolServices(id: 57, name: "BALIKESİR MUHARREM HASBİ ANADOLU LİSESİ", licensePlateId: 10),
                HighSchoolServices(id: 58, name: "BALIKESİR ALBAY CAFER TAYYAR NURAN OĞUZ ANADOLU LİSESİ", licensePlateId: 10),
                HighSchoolServices(id: 59, name: "BALIKESİR İSTANBULLUOĞLU SOSYAL BİLİMLER LİSESİ", licensePlateId: 10),
                HighSchoolServices(id: 60, name: "BURSA ÖZLÜCE ŞEHİT AYKUT YURTSEVER ANADOLU LİSESİ", licensePlateId: 16),
                HighSchoolServices(id: 61, name: "BURSA TOFAŞ FEN LİSESİ", licensePlateId: 16),
                HighSchoolServices(id: 62, name: "BURSA ŞAHİNLER ANADOLU LİSESİ", licensePlateId: 16),
                HighSchoolServices(id: 63, name: "BURSA BARIŞ ANADOLU LİSESİ", licensePlateId: 16),
                HighSchoolServices(id: 64, name: "BURSA ANADOLU LİSESİ", licensePlateId: 16),
                HighSchoolServices(id: 65, name: "BURSA ATATÜRK ANADOLU LİSESİ", licensePlateId: 16),
                HighSchoolServices(id: 66, name: "BURSA HÜRRİYET MESLEKİ TEKNİK VE ANADOLU LİSESİ", licensePlateId: 16),
                HighSchoolServices(id: 67, name: "BURSA OTOMOTİV İHRACATÇILARI BİRLİĞİ MTAL", licensePlateId: 16),
                HighSchoolServices(id: 68, name: "BURSA TURGUTALP ANADOLU LİSESİ", licensePlateId: 16),
                HighSchoolServices(id: 69, name: "BURSA NAİRE ÇİKAYEVA ANADOLU LİSESİ", licensePlateId: 16),
                HighSchoolServices(id: 70, name: "BURSA ZEKİ KONUKOĞLU ANADOLU LİSESİ", licensePlateId: 16),
                HighSchoolServices(id: 71, name: "BURSA YUNUS EMRE MESLEKİ TEKNİK ANADOLU LİSESİ", licensePlateId: 16),
                HighSchoolServices(id: 72, name: "BURSA HALİL İNANCIK SOSYAL BİLİMLER LİSESİ", licensePlateId: 16),
                HighSchoolServices(id: 73, name: "BURSA MEDİHA HAYRİ ÇELİK FEN LİSESİ", licensePlateId: 16),
                HighSchoolServices(id: 74, name: "DENİZLİ HASAN TEKİN ADA ANADOLU LİSESİ", licensePlateId: 20),
                HighSchoolServices(id: 75, name: "DENİZLİ ATATÜRK MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 20),
                HighSchoolServices(id: 76, name: "DENİZLİ FEN LİSESİ", licensePlateId: 20),
                HighSchoolServices(id: 77, name: "DENİZLİ KAZIM KAYNAK ANADOLU LİSESİ", licensePlateId: 20),
                HighSchoolServices(id: 78, name: "DENİZLİ MUSTAFA KAYNAK ANADOLU LİSESİ", licensePlateId: 20),
                HighSchoolServices(id: 79, name: "DENİZLİ CUMHURİYET ANADOLU LİSESİ", licensePlateId: 20),
                HighSchoolServices(id: 80, name: "DİYARBAKIR REKABET KURUMU ANADOLU LİSESİ", licensePlateId: 21),
                HighSchoolServices(id: 81, name: "DİYARBAKIR ANADOLU LİSESİ", licensePlateId: 21),
                HighSchoolServices(id: 82, name: "DİYARBAKIR ŞEHİT MEHMET BORA TAYFUR ANADOLU LİSESİ", licensePlateId: 21),
                HighSchoolServices(id: 83, name: "DİYARBAKIR FATİH SULTAN MEHMET ANADOLU LİSESİ", licensePlateId: 21),
                HighSchoolServices(id: 84, name: "DİYARBAKIR NEVZAT AYAZ ANADOLU LİSESİ", licensePlateId: 21),
                HighSchoolServices(id: 85, name: "DÜZCE FEN LİSESİ", licensePlateId: 81),
                HighSchoolServices(id: 86, name: "DÜZCE TURGUT ÖZAL ANADOLU LİSESİ", licensePlateId: 81),
                HighSchoolServices(id: 87, name: "DÜZCE 15 TEMMUZ ŞEHİTLER ANADOLU LİSESİ", licensePlateId: 81),
                HighSchoolServices(id: 88, name: "DÜZCE ARSAL ANADOLU LİSESİ", licensePlateId: 81),
                HighSchoolServices(id: 89, name: "DÜZCE BORSA İSTANBUL MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 81),
                HighSchoolServices(id: 90, name: "DÜZCE YAVUZ SELİM MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 81),
                HighSchoolServices(id: 91, name: "DÜZCE MEVLANA MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 81),
                HighSchoolServices(id: 92, name: "ELAZIĞ KAYA KARAKAYA FEN LİSESİ", licensePlateId: 23),
                HighSchoolServices(id: 93, name: "ELAZIĞ CEMİL MERİÇ FEN LİSESİ", licensePlateId: 23),
                HighSchoolServices(id: 94, name: "ELAZIĞ ANADOLU LİSESİ", licensePlateId: 23),
                HighSchoolServices(id: 95, name: "ELAZIĞ AHMET KABAKLI ANADOLU LİSESİ", licensePlateId: 23),
                HighSchoolServices(id: 96, name: "ELAZIĞ MEHMET KOLOĞLU ANADOLU LİSESİ", licensePlateId: 23),
                HighSchoolServices(id: 97, name: "ELAZIĞ ÇUBUK BEY ANADOLU LİSESİ", licensePlateId: 23),
                HighSchoolServices(id: 98, name: "ELAZIĞ ATATÜRK ANADOLU LİSESİ", licensePlateId: 23),
                HighSchoolServices(id: 99, name: "ELAZIĞ BALAKGAZİ ANADOLU LİSESİ", licensePlateId: 23),
                HighSchoolServices(id: 100, name: "ERZURUM NEVZAT KARABAĞ ANADOLU LİSESİ", licensePlateId: 25),
                HighSchoolServices(id: 101, name: "ERZURUM ZİYA GÖKALP ANADOLU LİSESİ", licensePlateId: 25),
                HighSchoolServices(id: 102, name: "ERZURUM MEHMET AKİF ERSOY ANADOLU LİSESİ", licensePlateId: 25),
                HighSchoolServices(id: 103, name: "ERZURUM İMKB ANADOLU LİSESİ", licensePlateId: 25),
                HighSchoolServices(id: 104, name: "ERZURUM ATATÜRK MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 25),
                HighSchoolServices(id: 105, name: "ERZURUM TEVFİK İLERİ ANADOLU LİSESİ", licensePlateId: 25),
                HighSchoolServices(id: 106, name: "ERZURUM ANADOLU LİSESİ", licensePlateId: 25),
                HighSchoolServices(id: 107, name: "ERZURUM LİSESİ", licensePlateId: 25),
                HighSchoolServices(id: 108, name: "ERZURUM ATATÜRK ANADOLU LİSESİ", licensePlateId: 25),
                HighSchoolServices(id: 109, name: "ERZURUM HACI SAMİ BOYDAK ANADOLU LİSESİ", licensePlateId: 25),
                HighSchoolServices(id: 110, name: "GAZİANTEP YASEMİN ERMAN BASLU ANADOLU LİSESİ ", licensePlateId: 27),
                HighSchoolServices(id: 111, name: "GAZİANTEP ANADOLU LİSESİ", licensePlateId: 27),
                HighSchoolServices(id: 112, name: "GAZİANTEP AYTEN KEMAL AKINAL ANADOLU LİSESİ", licensePlateId: 27),
                HighSchoolServices(id: 113, name: "GAZİANTEP MUSTAFA GÜRBÜZ NECAT BAYEL ANADOLU LİSESİ", licensePlateId: 27),
                HighSchoolServices(id: 114, name: "GAZİANTEP HATİCE-LÜTFÜ AKCAN ANADOLU LİSESİ", licensePlateId: 27),
                HighSchoolServices(id: 115, name: "GAZİANTEP İMKB ANADOLU LİSESİ", licensePlateId: 27),
                HighSchoolServices(id: 116, name: "GAZİANTEP VEDAT TOPÇUOĞLU ANADOLU LİSESİ", licensePlateId: 27),
                HighSchoolServices(id: 117, name: "GAZİANTEP İNCİ KONUKOĞLU ANADOLU LİSESİ", licensePlateId: 27),
                HighSchoolServices(id: 118, name: "GAZİANTEP ÖZEL İDARE ANADOLU LİSESİ", licensePlateId: 27),
                HighSchoolServices(id: 119, name: "GAZİANTEP AKŞEMSEDDİN ANADOLU LİSESİ", licensePlateId: 27),
                HighSchoolServices(id: 120, name: "HATAY ŞEMSETTİN MURSALOĞLU ANADOLU LİSESİ", licensePlateId: 31),
                HighSchoolServices(id: 121, name: "HATAY MAKZUME ANADOLU LİSESİ", licensePlateId: 31),
                HighSchoolServices(id: 122, name: "HATAY İSKENDERUN ANADOLU LİSESİ", licensePlateId: 31),
                HighSchoolServices(id: 123, name: "HATAY İSKENDERUN MESLEK LİSESİ", licensePlateId: 31),
                HighSchoolServices(id: 124, name: "HATAY BARBAROS MESLEK LİSESİ",licensePlateId: 31),
                HighSchoolServices(id: 125, name: "ISPARTA GÜLKENT ANADOLU LİSESİ", licensePlateId: 32),
                HighSchoolServices(id: 126, name: "ISPARTA AHMET MELİH DOĞAN ANADOLU LİSESİ", licensePlateId: 32),
                HighSchoolServices(id: 127, name: "ISPARTA TENZİLE ERDOĞAN ANADOLU LİSESİ", licensePlateId: 32),
                HighSchoolServices(id: 128, name: "ISPARTA ŞEHİT ALİ İHSAN KALMAZ ANADOLU LİSESİ", licensePlateId: 32),
                HighSchoolServices(id: 129, name: "ISPARTA MUSTAFA KAÇIKOÇ ANADOLU LİSESİ", licensePlateId: 32),
                HighSchoolServices(id: 130, name: "ISPARTA MUSTAFA GÜRKAN ANADOLU LİSESİ", licensePlateId: 32),
                HighSchoolServices(id: 131, name: "ISPARTA PROF. DR.TURAN YAZGAN ANADOLU LİSESİ", licensePlateId: 32),
                HighSchoolServices(id: 132, name: "ISPARTA 15 TEMMUZ ŞEHİTLERİ ANADOLU LİSESİ", licensePlateId: 32),
                HighSchoolServices(id: 133, name: "İSTANBUL ATAŞEHİR ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 134, name: "İSTANBUL ADNAN MENDERES ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 135, name: "İSTANBUL BAHÇELİEVLER ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 136, name: "İSTANBUL DEDE KORKUT ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 137, name: "İSTANBUL FÜSUN YÖNDER ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 138, name: "İSTANBUL KEMAL HASOĞLU ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 139, name: "İSTANBUL BAHÇELİEVLER AYDIN DOĞAN MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 140, name: "İSTANBUL İMMİB ERKAN AVCI MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 141, name: "İSTANBUL DEDE KORKUT ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 142, name: "İSTANBUL BAHÇELİEVLER AYDIN DOĞAN MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 143, name: "İSTANBUL BAHÇELİEVLER CUMHURİYET ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 144, name: "İSTANBUL İHKİB YENİBOSNA MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 145, name: "İSTANBUL YAHYA KEMAL BEYATLI ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 146, name: "İSTANBUL ATAKÖY ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 147, name: "İSTANBUL YEŞİLKÖY ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 148, name: "İSTANBUL HASAN POLATKAN ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 149, name: "İSTANBUL YEŞİLKÖY 50. YIL ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 150, name: "İSTANBUL YAHYA KEMAL BEYATLI ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 151, name: "İSTANBUL HÜSEYİN BÜRGE ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 152, name: "İSTANBUL TİCARET ODASI MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 153, name: "İSTANBUL SAKIP SABANCI ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 154, name: "İSTANBUL BİNGÜL ERDEM ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 155, name: "İSTANBUL SEMİHA AYVERDİ ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 156, name: "İSTANBUL ERGÜN ÖNER – MEHMET ÖNER ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 157, name: "İSTANBUL KADIKÖY ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 158, name: "İSTANBUL KADIKÖY LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 159, name: "İSTANBUL MEHMET BEYAZID ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 160, name: "İSTANBUL MUSTAFA SAFFET ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 161, name: "İSTANBUL AŞIK VEYSEL ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 162, name: "İSTANBUL HABİRE YAHŞİ ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 163, name: "İSTANBUL HAYRULLAH KEFOĞLU ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 164, name: "İSTANBUL ATATÜRK FEN LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 165, name: "İSTANBUL KADIKÖY ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 166, name: "İSTANBUL 50. YIL TAHRAN ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 167, name: "İSTANBUL KAZIM İŞMEN ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 168, name: "İSTANBUL KARTAL ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 169, name: "İSTANBUL SEMİHA ŞAKİR ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 170, name: "İSTANBUL BURAK BORA ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 171, name: "İSTANBUL YÜKSEL - İLHAN ALANYALI FEN LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 172, name: "İSTANBUL PROF. DR. SABAHATTİN ZAİM ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 173, name: "İSTANBUL ATAKENT İMKB MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 174, name: "İSTANBUL KÜÇÜKYALI REZAN HAS ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 175, name: "İSTANBUL MALTEPE MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 176, name: "İSTANBUL MALTEPE FEN LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 177, name: "İSTANBUL ŞİŞLİ ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 178, name: "İSTANBUL NİŞANTAŞI ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 179, name: "İSTANBUL NİŞANTAŞI NURİ AKIN ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 180, name: "İSTANBUL KURTULUŞ ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 181, name: "İSTANBUL ÜSKÜDAR VALİDEBAĞ FEN LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 182, name: "İSTANBUL ÇAĞRIBEY ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 183, name: "İSTANBUL ÜSKÜDAR BURHAN FELEK ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 184, name: "İSTANBUL HÜSEYİN AVNİ SÖZEN ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 185, name: "İSTANBUL HAYDARPAŞA ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 186, name: "İSTANBUL HACI SABANCI ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 187, name: "İSTANBUL HALİDE EDİP ADIVAR ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 188, name: "İSTANBUL BORSA İSTANBUL ZEYTİNBURNU ANADOLU LİSESİ", licensePlateId: 34),
                HighSchoolServices(id: 189, name: "İZMİR ŞEHİT BERSAN DOĞANTEKİN ÇOK PROGRAMLI ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 190, name: "İZMİR HALİT ÖZPİRİNÇ ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 191, name: "İZMİR MEHMET AKİF ERSOY ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 192, name: "İZMİR MUSTAFA KEMAL ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 193, name: "İZMİR ŞÜKRÜ SEHER ERGİL MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 194, name: "İZMİR HATİCE GÜZELCAN ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 195, name: "İZMİR BORNOVA ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 196, name: "İZMİR MASHAR ZORLU MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 197, name: "İZMİR FEN LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 198, name: "İZMİR BORNOVA SUPHİ KOYUNCU ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 199, name: "İZMİR BORNOVA MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 200, name: "İZMİR HAYRETTİN DURAN ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 201, name: "İZMİR FATMA SAYGIN ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 202, name: "İZMİR BUCA MEVLANA MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 203, name: "İZMİR ZÜBEYDE HANIM MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 204, name: "İZMİR BETONTAŞ ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 205, name: "İZMİR BUCA SULTAN ALPARSLAN ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 206, name: "İZMİR BUCA SÜLEYMAN ŞAH MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 207, name: "İZMİR ÜSKÜPLÜ SEBAHATTİN ÖZCAN MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 208, name: "İZMİR ŞİRİNYER ERTUĞRUL GAZİ ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 209, name: "İZMİR ÇİĞLİ TEĞMEN ALİ RIZA AKINCI ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 210, name: "İZMİR TUĞBA ÖZBEK ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 211, name: "İZMİR ÇİĞLİ NECİP FAZIL KISAKÜREK ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 212, name: "İZMİR GAZİ ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 213, name: "İZMİR EMLAKBANK SÜLEYMAN DEMİREL ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 214, name: "İZMİR VALİ EROL ÇAKIR ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 215, name: "İZMİR KARŞIYAKA BEHÇET UZ ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 216, name: "İZMİR KARŞIYAKA LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 217, name: "İZMİR KARŞIYAKA ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 218, name: "İZMİR KARŞIYAKA CİHAT KORA ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 219, name: "İZMİR KARŞIYAKA ATAKENT ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 220, name: "İZMİR SUZAN DİVRİK KIZ MESLEK LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 221, name: "İZMİR ŞEMİKLER ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 222, name: "İZMİR KONAK ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 223, name: "İZMİR KARATAŞ ANADOLU LİSESİ", licensePlateId: 35),
                HighSchoolServices(id: 224, name: "KARABÜK MEHMET VERGİLİ FEN LİSESİ", licensePlateId: 78),
                HighSchoolServices(id: 225, name: "KARABÜK ALPARSLAN GAZİ ANADOLU LİSESİ", licensePlateId: 78),
                HighSchoolServices(id: 226, name: "KARABÜK VAKIFBANK ZÜBEYDE HANIM ANADOLU LİSESİ", licensePlateId: 78),
                HighSchoolServices(id: 227, name: "KARABÜK 75.YIL KARABÜK ANADOLU LİSESİ", licensePlateId: 78),
                HighSchoolServices(id: 228, name: "KARABÜK FATİH SULTAN MEHMET ANADOLU LİSESİ(SAFRANBOLU)", licensePlateId: 78),
                HighSchoolServices(id: 229, name: "KARABÜK DEMİRÇELİK ANADOLU LİSESİ", licensePlateId: 78),
                HighSchoolServices(id: 230, name: "KARABÜK CUMHURİYET ANADOLU LİSESİ", licensePlateId: 78),
                HighSchoolServices(id: 231, name: "KARABÜK KIYMET VE MUSTAFA YAZICI ANADOLU LİSESİ", licensePlateId: 78),
                HighSchoolServices(id: 232, name: "KARABÜK MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 78),
                HighSchoolServices(id: 233, name: "KARABÜK FEVZİ ÇAKMAK ANADOLU LİSESİ", licensePlateId: 78),
                HighSchoolServices(id: 234, name: "KAYSERİ SEYİDE DALOĞLU ANADOLU LİSESİ", licensePlateId: 38),
                HighSchoolServices(id: 235, name: "KAYSERİ FEVZİ ÇAKMAK ANADOLU LİSESİ", licensePlateId: 38),
                HighSchoolServices(id: 236, name: "KAYSERİ TALAS ANADOLU LİSESİ", licensePlateId: 38),
                HighSchoolServices(id: 237, name: "KAYSERİ ANADOLU LİSESİ", licensePlateId: 38),
                HighSchoolServices(id: 238, name: "KAYSERİ AYDINLIKEVLER ANADOLU LİSESİ", licensePlateId: 38),
                HighSchoolServices(id: 239, name: "KAYSERİ SELÇUKLU ANADOLU LİSESİ", licensePlateId: 38),
                HighSchoolServices(id: 240, name: "KAYSERİ MUSTAFA ERASLAN ANADOLU LİSESİ", licensePlateId: 38),
                HighSchoolServices(id: 241, name: "KAYSERİ NUH MEHMET KÜÇÜKÇALIK ANADOLU LİSESİ", licensePlateId: 38),
                HighSchoolServices(id: 242, name: "KAYSERİ ERCİYES MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 38),
                HighSchoolServices(id: 243, name: "KAYSERİ KOCASİNAN MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 38),
                HighSchoolServices(id: 244, name: "KIRIKKALE ATATÜRK ANADOLU LİSESİ", licensePlateId: 71),
                HighSchoolServices(id: 245, name: "KIRIKKALE MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 71),
                HighSchoolServices(id: 246, name: "KIRIKKALE YILDIRIM BEYAZIT ANADOLU LİSESİ", licensePlateId: 71),
                HighSchoolServices(id: 247, name: "KIRIKKALE MEHMET AKİF ERSOY ANADOLU LİSESİ", licensePlateId: 71),
                HighSchoolServices(id: 248, name: "KIRIKKALE SÜLEYMAN DEMİREL ANADOLU LİSESİ", licensePlateId: 71),
                HighSchoolServices(id: 249, name: "KOCAELİ GAZİ  ANADOLU LİSESİ", licensePlateId: 41),
                HighSchoolServices(id: 250, name: "KOCAELİ SABANCI MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 41),
                HighSchoolServices(id: 251, name: "KOCAELİ İZMİT ANADOLU LİSESİ", licensePlateId: 41),
                HighSchoolServices(id: 252, name: "KOCAELİ MERKEZ BANKASI DERİNCE ANADOLU LİSESİ", licensePlateId: 41),
                HighSchoolServices(id: 253, name: "KOCAELİ ŞEHİT EDİP ZENGİN ANADOLU LİSESİ", licensePlateId: 41),
                HighSchoolServices(id: 254, name: "KOCAELİ GÖKŞEN M.YÜCEL ANADOLU LİSESİ", licensePlateId: 41),
                HighSchoolServices(id: 255, name: "KONYA SELÇUKLU ANADOLU LİSESİ", licensePlateId: 42),
                HighSchoolServices(id: 256, name: "KONYA MEHMET AKİF ANADOLU LİSESİ", licensePlateId: 42),
                HighSchoolServices(id: 257, name: "KONYA SELÇUKLU CUMHURİYET ANADOLU LİSESİ", licensePlateId: 42),
                HighSchoolServices(id: 258, name: "KONYA DOLAPOĞLU ANADOLU LİSESİ", licensePlateId: 42),
                HighSchoolServices(id: 259, name: "KONYA ATATÜRK ANADOLU LİSESİ", licensePlateId: 42),
                HighSchoolServices(id: 260, name: "KONYA LİSESİ", licensePlateId: 42),
                HighSchoolServices(id: 261, name: "KONYA MERAM ANADOLU LİSESİ", licensePlateId: 42),
                HighSchoolServices(id: 262, name: "KONYA ADİL KARAAĞAÇ MTAL", licensePlateId: 42),
                HighSchoolServices(id: 263, name: "MANİSA GEDİZ ANADOLU LİSESİ", licensePlateId: 45),
                HighSchoolServices(id: 264, name: "MANİSA HASAN TÜREK ANADOLU LİSESİ", licensePlateId: 45),
                HighSchoolServices(id: 265, name: "MANİSA DÜNDAR ÇİLOĞLU ANADOLU LİSESİ", licensePlateId: 45),
                HighSchoolServices(id: 266, name: "MANİSA TOBB BÜLENT KOŞMAZ FEN LİSESİ", licensePlateId: 45),
                HighSchoolServices(id: 267, name: "MANİSA FATİH ANADOLU LİSESİ", licensePlateId: 45),
                HighSchoolServices(id: 268, name: "MANİSA FEN LİSESİ", licensePlateId: 45),
                HighSchoolServices(id: 269, name: "MERSİN YUSUF KALKAVAN ANADOLU LİSESİ", licensePlateId: 33),
                HighSchoolServices(id: 270, name: "MERSİN SALİM YILMAZ ANADOLU LİSESİ", licensePlateId: 33),
                HighSchoolServices(id: 271, name: "MERSİN İÇEL ANADOLU LİSESİ", licensePlateId: 33),
                HighSchoolServices(id: 272, name: "MERSİN MAHMUT ARSLAN ANADOLU LİSESİ", licensePlateId: 33),
                HighSchoolServices(id: 273, name: "MERSİN EYÜP AYGAR ANADOLU LİSESİ", licensePlateId: 33),
                HighSchoolServices(id: 274, name: "MERSİN AKİB ZAFER ÇAĞLAYAN MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 33),
                HighSchoolServices(id: 275, name: "MERSİN TEVFİK SIRRI GÜR ANADOLU LİSESİ", licensePlateId: 33),
                HighSchoolServices(id: 276, name: "MUĞLA ANADOLU LİSESİ", licensePlateId: 48),
                HighSchoolServices(id: 277, name: "MUĞLA GAZİ ANADOLU LİSESİ", licensePlateId: 48),
                HighSchoolServices(id: 278, name: "MUĞLA 75. YIL FEN LİSESİ", licensePlateId: 48),
                HighSchoolServices(id: 279, name: "MUĞLA TURGUTREİS ANADOLU LİSESİ", licensePlateId: 48),
                HighSchoolServices(id: 280, name: "MUĞLA MENTEŞE SOSYAL BİLİMLER LİSESİ", licensePlateId: 48),
                HighSchoolServices(id: 281, name: "MUĞLA BAYIR ANADOLU LİSESİ", licensePlateId: 48),
                HighSchoolServices(id: 282, name: "SAKARYA NECMETTİN ERBAKAN FEN LİSESİ", licensePlateId: 54),
                HighSchoolServices(id: 283, name: "SAKARYA 15 TEMMUZ ŞEHİTLERİ FEN LİSESİ", licensePlateId: 54),
                HighSchoolServices(id: 284, name: "SAKARYA ANADOLU LİSESİ", licensePlateId: 54),
                HighSchoolServices(id: 285, name: "SAKARYA ŞEHİT ÜSTEĞMEN SELÇUK ESEDOĞLU LİSESİ", licensePlateId: 54),
                HighSchoolServices(id: 286, name: "SAKARYA MİTHAT PAŞA ANADOLU LİSESİ", licensePlateId: 54),
                HighSchoolServices(id: 287, name: "SAMSUN ANADOLU LİSESİ", licensePlateId: 54),
                HighSchoolServices(id: 288, name: "SAMSUN ANAFARTALAR ANADOLU LİSESİ", licensePlateId: 54),
                HighSchoolServices(id: 289, name: "SAMSUN ATAKUM ANADOLU LİSESİ", licensePlateId: 54),
                HighSchoolServices(id: 290, name: "SAMSUN CUMHURİYET ANADOLU LİSESİ", licensePlateId: 54),
                HighSchoolServices(id: 291, name: "SAMSUN HURİYE SÜER ANADOLU LİSESİ", licensePlateId: 54),
                HighSchoolServices(id: 292, name: "SAMSUN ONUR ATEŞ ANADOLU LİSESİ", licensePlateId: 54),
                HighSchoolServices(id: 293, name: "SAMSUN CANİK İMKB ANADOLU LİSESİ", licensePlateId: 54),
                HighSchoolServices(id: 294, name: "SAMSUN ATATÜRK ANADOLU LİSESİ", licensePlateId: 54),
                HighSchoolServices(id: 295, name: "SAMSUN YEŞİLKENT ANADOLU LİSESİ", licensePlateId: 54),
                HighSchoolServices(id: 296, name: "SİNOP SARI SALTUK ANADOLU LİSESİ", licensePlateId: 57),
                HighSchoolServices(id: 297, name: "SİNOP ATATÜRK ANADOLU LİSESİ", licensePlateId: 57),
                HighSchoolServices(id: 298, name: "SİNOP ANADOLU LİSESİ", licensePlateId: 57),
                HighSchoolServices(id: 299, name: "ŞANLIURFA ÇEAŞ ANADOLU LİSESİ", licensePlateId: 63),
                HighSchoolServices(id: 300, name: "ŞANLIURFA ANADOLU LİSESİ", licensePlateId: 63),
                HighSchoolServices(id: 301, name: "ŞANLIURFA İMKB ÇOK PROGRAMLI ANADOLU LİSESİ", licensePlateId: 63),
                HighSchoolServices(id: 302, name: "ŞANLIURFA SÜLEYMANİYE MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 63),
                HighSchoolServices(id: 303, name: "ŞANLIURFA YÜZBAŞI ALİ SAİP ANADOLU LİSESİ", licensePlateId: 63),
                HighSchoolServices(id: 304, name: "TEKİRDAĞ ANADOLU LİSESİ", licensePlateId: 59),
                HighSchoolServices(id: 305, name: "TEKİRDAĞ NAMIK KEMAL LİSESİ", licensePlateId: 59),
                HighSchoolServices(id: 306, name: "TEKİRDAĞ EBRU NAİM FEN LİSESİ", licensePlateId: 59),
                HighSchoolServices(id: 307, name: "TEKİRDAĞ BELEDİYESİ SOSYAL BİLİMLER LİSESİ", licensePlateId: 59),
                HighSchoolServices(id: 308, name: "TEKİRDAĞ ZÜBEYDE HANIM MESLEKİ VE TEKNİK ANADOLU LİSESİ", licensePlateId: 59),
                HighSchoolServices(id: 309, name: "TOKAT İMKB SOSYAL BİLİMLER LİSESİ", licensePlateId: 60),
                HighSchoolServices(id: 310, name: "TOKAT GAZİ OSMAN PAŞA LİSESİ", licensePlateId: 60),
                HighSchoolServices(id: 311, name: "TRABZON YAVUZ SULTAN SELİM ANADOLU LİSESİ", licensePlateId: 61),
                HighSchoolServices(id: 312, name: "TRABZON FATİH SULTAN MEHMET ANADOLU LİSESİ", licensePlateId: 61),
                HighSchoolServices(id: 313, name: "TRABZON TEVFİK SERDAR ANADOLU LİSESİ", licensePlateId: 61),
                HighSchoolServices(id: 314, name: "TRABZON KANUNİ ANADOLU LİSESİ", licensePlateId: 61),
                HighSchoolServices(id: 315, name: "TRABZON AFFAN KİTAPÇIOĞLU ANADOLU LİSESİ", licensePlateId: 61),
                HighSchoolServices(id: 316, name: "TRABZON 88. CUMHURİYET ANADOLU LİSESİ", licensePlateId: 61),
                HighSchoolServices(id: 317, name: "TRABZON 15 TEMMUZ ŞEHİTLERİ ANADOLU LİSESİ", licensePlateId: 61),
                HighSchoolServices(id: 318, name: "TRABZON MAHMUT CELALETTİN ÖKTEN ANADOLU LİSESİ", licensePlateId: 61),
                HighSchoolServices(id: 319, name: "TRABZON SOSYAL BİLİMLER LİSESİ", licensePlateId: 61),
                HighSchoolServices(id: 320, name: "TRABZON GAZİ ANADOLU LİSESİ", licensePlateId: 61),
                HighSchoolServices(id: 321, name: "ZONGULDAK BAŞÖĞRETMEN ANADOLU LİSESİ", licensePlateId: 67),
                HighSchoolServices(id: 322, name: "ZONGULDAK FEN LİSESİ", licensePlateId: 67),
                HighSchoolServices(id: 323, name: "ZONGULDAK MEHMET ÇELİKEL LİSESİ", licensePlateId: 67),
                HighSchoolServices(id: 324, name: "ZONGULDAK ATATÜRK ANADOLU LİSESİ", licensePlateId: 67)
        ]
    }
    
    static func getName(by id: Int) -> String {
        switch id {
        default:
            return HighSchoolServices.allHighSchoolList()[id].name
        }
    }
    
    static func getLicensePlateId(by id: Int) -> Int {
        switch id {
        default:
            return HighSchoolServices.allHighSchoolList()[id].licensePlateId
        }
    }
    
    static func getID(by licensePlateId: Int) -> Int {
        switch licensePlateId {
        default:
            return HighSchoolServices.allHighSchoolList()[licensePlateId - 1].id
        }
    }
    
    static func getNameWithLicensePlateId(by licensePlateId: Int) -> String {
        switch licensePlateId {
        default:
            return HighSchoolServices.allHighSchoolList()[licensePlateId - 1].name
        }
    }
}


