//
//  UniversityServices.swift
//  lyie
//
//  Created by Sevcan Eşim on 10.01.2021.
//

import Foundation
import UIKit

struct UniversityServices {
    var id: Int
    var name: String
    var licensePlateId: Int
    
    static func allUniversityList() -> [UniversityServices] {
        return [UniversityServices(id: 0, name: "Abdullah Gül Üniversitesi", licensePlateId: 38),
                UniversityServices(id: 1, name: "Adana Alparslan Türkeş Bilim ve Teknoloji  Üniversitesi", licensePlateId: 1),
                UniversityServices(id: 2, name: "Adıyaman Üniversitesi", licensePlateId: 2),
                UniversityServices(id: 3, name: "Afyon Kocatepe Üniversitesi", licensePlateId: 3),
                UniversityServices(id: 4, name: "Afyonkarahisar Sağlık Bilimleri Üniversitesi", licensePlateId: 3),
                UniversityServices(id: 5, name: "Akdeniz Üniversitesi", licensePlateId: 7),
                UniversityServices(id: 6, name: "Aksaray Üniversitesi", licensePlateId: 68),
                UniversityServices(id: 7, name: "Alanya Alaaddin Keykubat Üniversitesi", licensePlateId: 7),
                UniversityServices(id: 8, name: "Amasya Üniversitesi", licensePlateId: 5),
                UniversityServices(id: 9, name: "Anadolu Üniversitesi", licensePlateId: 26),
                UniversityServices(id: 10, name: "Ankara Hacı Bayram Veli Üniversitesi", licensePlateId: 6),
                UniversityServices(id: 11, name: "Ankara Müzik ve Güzel Sanatlar Üniversitesi", licensePlateId: 6),
                UniversityServices(id: 12, name: "Ankara Sosyal Bilimler Üniversitesi", licensePlateId: 6),
                UniversityServices(id: 13, name: "Ankara Yıldırım Beyazıt Üniversitesi", licensePlateId: 6),
                UniversityServices(id: 14, name: "Ankara Üniversitesi", licensePlateId: 6),
                UniversityServices(id: 15, name: "Ardahan Üniversitesi", licensePlateId: 75),
                UniversityServices(id: 16, name: "Artvin Çoruh Üniversitesi", licensePlateId: 8),
                UniversityServices(id: 17, name: "Atatürk Üniversitesi", licensePlateId: 25),
                UniversityServices(id: 18, name: "Aydın Adnan Menderes Üniversitesi", licensePlateId: 9),
                UniversityServices(id: 19, name: "Ağrı İbrahim Çeçen Üniversitesi", licensePlateId: 4),
                UniversityServices(id: 20, name: "Balıkesir Üniversitesi", licensePlateId: 10),
                UniversityServices(id: 21, name: "Bandırma Onyedi Eylül Üniversitesi", licensePlateId: 10),
                UniversityServices(id: 22, name: "Bartın Üniversitesi", licensePlateId: 74),
                UniversityServices(id: 23, name: "Batman Üniversitesi", licensePlateId: 72),
                UniversityServices(id: 24, name: "Bayburt Üniversitesi", licensePlateId: 69),
                UniversityServices(id: 25, name: "Bilecik Şeyh Edebali Üniversitesi", licensePlateId: 11),
                UniversityServices(id: 26, name: "Bingöl Üniversitesi", licensePlateId: 12),
                UniversityServices(id: 27, name: "Bitlis Eren Üniversitesi", licensePlateId: 13),
                UniversityServices(id: 28, name: "Bolu Abant İzzet Baysal Üniversitesi", licensePlateId: 14),
                UniversityServices(id: 29, name: "Boğaziçi Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 30, name: "Burdur Mehmet Akif Ersoy", licensePlateId: 15),
                UniversityServices(id: 31, name: "Bursa Teknik Üniversitesi", licensePlateId: 16),
                UniversityServices(id: 32, name: "Bursa Uludağ Üniversitesi", licensePlateId: 16),
                UniversityServices(id: 33, name: "Çanakkale Onsekiz Mart Üniversitesi", licensePlateId: 17),
                UniversityServices(id: 34, name: "Çankırı Karatekin Üniversitesi", licensePlateId: 18),
                UniversityServices(id: 35, name: "Çukurova Üniversitesi", licensePlateId: 1),
                UniversityServices(id: 36, name: "Dicle Üniversitesi", licensePlateId: 21),
                UniversityServices(id: 37, name: "Dokuz Eylül Üniversitesi", licensePlateId: 35),
                UniversityServices(id: 38, name: "Düzce Üniversitesi", licensePlateId: 81),
                UniversityServices(id: 39, name: "Ege Üniversitesi", licensePlateId: 35),
                UniversityServices(id: 40, name: "Erciyes Üniversitesi", licensePlateId: 38),
                UniversityServices(id: 41, name: "Erzincan Binali Yıldırım Üniversitesi", licensePlateId: 24),
                UniversityServices(id: 42, name: "Erzurum Teknik Üniversitesi", licensePlateId: 25),
                UniversityServices(id: 43, name: "Eskişehir Osmangazi Üniversitesi", licensePlateId: 26),
                UniversityServices(id: 44, name: "Eskişehir Teknik Üniversitesi", licensePlateId: 26),
                UniversityServices(id: 45, name: "Fırat Üniversitesi", licensePlateId: 23),
                UniversityServices(id: 46, name: "Galatasaray Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 47, name: "Gazi Üniversitesi", licensePlateId: 6),
                UniversityServices(id: 48, name: "Gaziantep Bilim ve Teknoloji Üniversitesi", licensePlateId: 27),
                UniversityServices(id: 49, name: "Gaziantep Üniversitesi", licensePlateId: 27),
                UniversityServices(id: 50, name: "Gebze Teknik Üniversitesi", licensePlateId: 41),
                UniversityServices(id: 51, name: "Giresun Üniversitesi", licensePlateId: 28),
                UniversityServices(id: 52, name: "Gümüşhane Üniversitesi", licensePlateId: 29),
                UniversityServices(id: 53, name: "Hacettepe Üniversitesi", licensePlateId: 6),
                UniversityServices(id: 54, name: "Hakkari Üniversitesi", licensePlateId: 30),
                UniversityServices(id: 55, name: "Harran Üniversitesi", licensePlateId: 63),
                UniversityServices(id: 56, name: "Hatay Mustafa Kemal Üniversitesi", licensePlateId: 31),
                UniversityServices(id: 57, name: "Hitit Üniversitesi", licensePlateId: 19),
                UniversityServices(id: 58, name: "Isparta Uygulamalı Bilimler Üniversitesi", licensePlateId: 32),
                UniversityServices(id: 59, name: "Iğdır Üniversitesi", licensePlateId: 76),
                UniversityServices(id: 60, name: "İnönü Üniversitesi", licensePlateId: 44),
                UniversityServices(id: 61, name: "İskenderun Teknik Üniversitesi", licensePlateId: 31),
                UniversityServices(id: 62, name: "İstanbul Medeniyet Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 63, name: "İstanbul Teknik Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 64, name: "İstanbul Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 65, name: "İstanbul Üniversitesi-Cerrahpaşa", licensePlateId: 34),
                UniversityServices(id: 66, name: "İzmir Bakırçay Üniversitesi", licensePlateId: 35),
                UniversityServices(id: 67, name: "İzmir Demokrasi Üniversitesi", licensePlateId: 35),
                UniversityServices(id: 68, name: "İzmir Katip Çelebi Üniversitesi", licensePlateId: 35),
                UniversityServices(id: 69, name: "İzmir Yüksek Teknoloji Enstitüsü", licensePlateId: 35),
                UniversityServices(id: 70, name: "Kafkas Üniversitesi", licensePlateId: 36),
                UniversityServices(id: 71, name: "Kahramanmaraş İstiklal Üniversitesi ", licensePlateId: 46),
                UniversityServices(id: 72, name: "Kahramanmaraş Sütçü İmam Üniversitesi", licensePlateId: 46),
                UniversityServices(id: 73, name: "Karabük Üniversitesi", licensePlateId: 78),
                UniversityServices(id: 74, name: "Karadeniz Teknik Üniversitesi", licensePlateId: 61),
                UniversityServices(id: 75, name: "Karamanoğlu Mehmetbey Üniversitesi", licensePlateId: 70),
                UniversityServices(id: 76, name: "Kastamonu Üniversitesi", licensePlateId: 37),
                UniversityServices(id: 77, name: "Kayseri Üniversitesi", licensePlateId: 38),
                UniversityServices(id: 78, name: "Kilis 7 Aralık Üniversitesi", licensePlateId: 79),
                UniversityServices(id: 79, name: "Kocaeli Üniversitesi", licensePlateId: 41),
                UniversityServices(id: 80, name: "Konya Teknik Üniversitesi", licensePlateId: 42),
                UniversityServices(id: 81, name: "Kütahya Dumlupınar Üniversitesi", licensePlateId: 43),
                UniversityServices(id: 82, name: "Kütahya Sağlık Bilimleri Üniversitesi", licensePlateId: 43),
                UniversityServices(id: 83, name: "Kırıkkale Üniversitesi", licensePlateId: 71),
                UniversityServices(id: 84, name: "Kırklareli Üniversitesi", licensePlateId: 39),
                UniversityServices(id: 85, name: "Kırşehir Ahi Evran Üniversitesi", licensePlateId: 40),
                UniversityServices(id: 86, name: "Malatya Turgut Özal Üniversitesi", licensePlateId: 44),
                UniversityServices(id: 87, name: "Manisa Celal Bayar Üniversitesi", licensePlateId: 45),
                UniversityServices(id: 88, name: "Mardin Artuklu Üniversitesi", licensePlateId: 47),
                UniversityServices(id: 89, name: "Marmara Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 90, name: "Mersin Üniversitesi", licensePlateId: 33),
                UniversityServices(id: 91, name: "Mimar Sinan Güzel Sanatlar Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 92, name: "Muğla Sıtkı Koçman Üniversitesi", licensePlateId: 48),
                UniversityServices(id: 93, name: "Munzur Üniversitesi", licensePlateId: 62),
                UniversityServices(id: 94, name: "Muş Alparslan Üniversitesi", licensePlateId: 49),
                UniversityServices(id: 95, name: "Necmettin Erbakan Üniversitesi", licensePlateId: 42),
                UniversityServices(id: 96, name: "Nevşehir Hacı Bektaş Veli Üniversitesi", licensePlateId: 50),
                UniversityServices(id: 97, name: "Niğde Ömer Halidemir Üniversitesi", licensePlateId: 51),
                UniversityServices(id: 98, name: "Ondokuz Mayıs Üniversitesi", licensePlateId: 55),
                UniversityServices(id: 99, name: "Ordu Üniversitesi", licensePlateId: 52),
                UniversityServices(id: 100, name: "Orta Doğu Teknik Üniversitesi", licensePlateId: 6),
                UniversityServices(id: 101, name: "Osmaniye Korkut Ata Üniversitesi", licensePlateId: 80),
                UniversityServices(id: 102, name: "Pamukkale Üniversitesi", licensePlateId: 20),
                UniversityServices(id: 103, name: "Recep Tayyip Erdoğan Üniversitesi", licensePlateId: 53),
                UniversityServices(id: 104, name: "Sağlık Bilimleri Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 105, name: "Sakarya Uygulamalı Bilimler Üniversitesi", licensePlateId: 54),
                UniversityServices(id: 106, name: "Sakarya Üniversitesi", licensePlateId: 54),
                UniversityServices(id: 107, name: "Samsun Üniversitesi", licensePlateId: 55),
                UniversityServices(id: 108, name: "Selçuk Üniversitesi", licensePlateId: 42),
                UniversityServices(id: 109, name: "Siirt Üniversitesi", licensePlateId: 56),
                UniversityServices(id: 110, name: "Sinop Üniversitesi", licensePlateId: 57),
                UniversityServices(id: 111, name: "Sivas Bilim ve Teknoloji Üniversitesi", licensePlateId: 58),
                UniversityServices(id: 112, name: "Sivas Cumhuriyet Üniversitesi", licensePlateId: 58),
                UniversityServices(id: 113, name: "Süleyman Demirel Üniversitesi", licensePlateId: 32),
                UniversityServices(id: 114, name: "Şırnak Üniversitesi", licensePlateId: 73),
                UniversityServices(id: 115, name: "Tarsus Üniversitesi", licensePlateId: 33),
                UniversityServices(id: 116, name: "Tekirdağ Namık Kemal Üniversitesi", licensePlateId: 59),
                UniversityServices(id: 117, name: "Tokat Gaziosmanpaşa Üniversitesi", licensePlateId: 60),
                UniversityServices(id: 118, name: "Trabzon Üniversitesi", licensePlateId: 61),
                UniversityServices(id: 119, name: "Trakya Üniversitesi", licensePlateId: 22),
                UniversityServices(id: 120, name: "Türk-Alman Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 121, name: "Türk-Japon Bilim ve Teknoloji Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 122, name: "Türkiye Uluslararası İslam, Bilim ve Teknoloji Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 123, name: "Uşak Üniversitesi", licensePlateId: 64),
                UniversityServices(id: 124, name: "Van Yüzüncü Yıl Üniversitesi", licensePlateId: 65),
                UniversityServices(id: 125, name: "Yalova Üniversitesi", licensePlateId: 77),
                UniversityServices(id: 126, name: "Yıldız Teknik Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 127, name: "Yozgat Bozok Üniversitesi", licensePlateId: 66),
                UniversityServices(id: 128, name: "Zonguldak Bülent Ecevit Üniversitesi", licensePlateId: 67),
                UniversityServices(id: 129, name: "Acıbadem Mehmet Ali Aydınlar Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 130, name: "Alanya Hamdullah Emin Paşa Üniversitesi", licensePlateId: 7),
                UniversityServices(id: 131, name: "Altınbaş Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 132, name: "Anka Teknoloji Üniversitesi", licensePlateId: 6),
                UniversityServices(id: 133, name: "Ankara Medipol Üniversitesi", licensePlateId: 6),
                UniversityServices(id: 134, name: "Antalya AKEV Üniversitesi", licensePlateId: 7),
                UniversityServices(id: 135, name: "Antalya Bilim Üniversitesi", licensePlateId: 7),
                UniversityServices(id: 136, name: "Ataşehir Adıgüzel Meslek Yüksekokulu", licensePlateId: 34),
                UniversityServices(id: 137, name: "Atılım Üniversitesi", licensePlateId: 6),
                UniversityServices(id: 138, name: "Avrasya Üniversitesi", licensePlateId: 61),
                UniversityServices(id: 139, name: "Avrupa Meslek Yüksekokulu", licensePlateId: 34),
                UniversityServices(id: 140, name: "Bahçeşehir Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 141, name: "Başkent Üniversitesi", licensePlateId: 6),
                UniversityServices(id: 142, name: "Beykent Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 143, name: "Beykoz Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 144, name: "Bezmiâlem Vakıf Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 145, name: "Biruni Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 146, name: "Çağ Üniversitesi", licensePlateId: 33),
                UniversityServices(id: 147, name: "Çankaya Üniversitesi", licensePlateId: 6),
                UniversityServices(id: 148, name: "Doğuş Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 149, name: "Faruk Saraç Tasarım Meslek Yüksekokulu", licensePlateId: 16),
                UniversityServices(id: 150, name: "Fatih Sultan Mehmet Vakıf Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 151, name: "Fenerbahçe Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 152, name: "Haliç Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 153, name: "Hasan Kalyoncu Üniversitesi", licensePlateId: 27),
                UniversityServices(id: 154, name: "Işık Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 155, name: "İhsan Doğramacı Bilkent Üniversitesi", licensePlateId: 6),
                UniversityServices(id: 156, name: "İstanbul 29 Mayıs Üniversites", licensePlateId: 34),
                UniversityServices(id: 157, name: "İstanbul Arel Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 158, name: "İstanbul Atlas Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 159, name: "İstanbul Aydın Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 160, name: "İstanbul Ayvansaray Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 161, name: "İstanbul Bilgi Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 162, name: "İstanbul Bilim Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 163, name: "İstanbul Esenyurt Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 164, name: "İstanbul Gedik Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 165, name: "İstanbul Gelişim Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 166, name: "İstanbul İbn Haldun Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 167, name: "İstanbul Kent Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 168, name: "İstanbul Kültür Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 169, name: "İstanbul Medipol Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 170, name: "İstanbul Okan Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 171, name: "İstanbul Rumeli Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 172, name: "İstanbul Sabahattin Zaim Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 173, name: "İstanbul Şehir Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 174, name: "İstanbul Şişli Meslek Yüksekokulu", licensePlateId: 34),
                UniversityServices(id: 175, name: "İstanbul Ticaret Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 176, name: "İstanbul Yeni Yüzyıl Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 177, name: "İstinye Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 178, name: "İzmir Ekonomi Üniversitesi", licensePlateId: 35),
                UniversityServices(id: 179, name: "İzmir Tınaztepe Üniversitesi", licensePlateId: 35),
                UniversityServices(id: 180, name: "Kadir Has Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 181, name: "Kapadokya Üniversitesi", licensePlateId: 50),
                UniversityServices(id: 182, name: "Kavram Meslek Yüksekokulu", licensePlateId: 34),
                UniversityServices(id: 183, name: "Koç Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 184, name: "Konya Gıda ve Tarım Üniversitesi", licensePlateId: 42),
                UniversityServices(id: 185, name: "KTO Karatay Üniversitesi", licensePlateId: 42),
                UniversityServices(id: 186, name: "Lokman Hekim Üniversitesi", licensePlateId: 6),
                UniversityServices(id: 187, name: "Maltepe Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 188, name: "MEF Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 189, name: "Nişantaşı Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 190, name: "Nuh Naci Yazgan Üniversitesi", licensePlateId: 38),
                UniversityServices(id: 191, name: "Ostim Teknik Üniversitesi", licensePlateId: 6),
                UniversityServices(id: 192, name: "Özyeğin Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 193, name: "Piri Reis Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 194, name: "Sabancı Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 195, name: "Sanko Üniversitesi", licensePlateId: 27),
                UniversityServices(id: 196, name: "Semerkand Bilim ve Medeniyet Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 197, name: "TED Üniversitesi", licensePlateId: 6),
                UniversityServices(id: 198, name: "TOBB Ekonomi ve Teknoloji Üniversitesi", licensePlateId: 6),
                UniversityServices(id: 199, name: "Toros Üniversitesi", licensePlateId: 33),
                UniversityServices(id: 200, name: "Türk Hava Kurumu Üniversitesi", licensePlateId: 6),
                UniversityServices(id: 201, name: "Ufuk Üniversitesi", licensePlateId: 6),
                UniversityServices(id: 202, name: "Üsküdar Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 203, name: "Yaşar Üniversitesi", licensePlateId: 35),
                UniversityServices(id: 204, name: "Yeditepe Üniversitesi", licensePlateId: 34),
                UniversityServices(id: 205, name: "Yüksek İhtisas Üniversitesi", licensePlateId: 6)]
    }
    
    static func getUniName(by id: Int) -> String {
        switch id {
        default:
            return UniversityServices.allUniversityList()[id].name
        }
    }
}



